### ISSUE TITLE
Test failures on Windows

### ISSUE THREAD

**Issue by pka** [georust/gdal#219]
When running tests in CI on Windows (#218) a few tests fail:

```
---- config::tests::test_clear_option_thread_local stdout ----
thread 'config::tests::test_clear_option_thread_local' panicked at 'assertion failed: `(left == right)`
  left: `"256"`,
 right: `"DEFAULT"`', src\config.rs:201:9

---- raster::tests::test_create_with_band_type_with_options stdout ----
thread 'raster::tests::test_create_with_band_type_with_options' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALCreate", msg: "Attempt to create new tiff file `/tmp/test.tif' failed: No error" }', src\raster\tests.rs:285:14

---- spatial_ref::tests::auto_identify stdout ----
thread 'spatial_ref::tests::auto_identify' panicked at 'called `Result::unwrap()` on an `Err` value: OgrError { err: 7, method_name: "OSRAutoIdentifyEPSG" }', src\spatial_ref\tests.rs:207:38

---- vector::vector_tests::tests::test_write_features stdout ----
thread 'vector::vector_tests::tests::test_write_features' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: Other, message: "The process cannot access the file because it is being used by another process." }', src\vector\vector_tests\mod.rs:660:53
```

Comments from @rmanoka:

1. `raster::tests::test_create_with_band_type_with_options` :  we're trying to create `/tmp/test.tif` which is not valid path in windows.  Should use a proper `env::temp_dir` for platform compat.
2. `vector::vector_tests::tests::test_write_features` : seems to be from `fs::remove_file` when the dataset is open.    Should remove the file after the dataset is dropped I guess.
3. `spatial_ref::tests::auto_identify`:  the error code is `OGRERR_UNSUPPORTED_SRS` so I suppose the GDAL installation is outdated / doesn't contain many coordinate systems?

**Comment by pka** [comment]
Current state:

```
failures:

---- raster::mdarray::tests::test_array_names stdout ----
thread 'raster::mdarray::tests::test_array_names' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:644:83
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- raster::mdarray::tests::test_attributes stdout ----
thread 'raster::mdarray::tests::test_attributes' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:834:85

---- raster::mdarray::tests::test_datatype stdout ----
thread 'raster::mdarray::tests::test_datatype' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:773:83

---- raster::mdarray::tests::test_dimension_name stdout ----
thread 'raster::mdarray::tests::test_dimension_name' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:693:83

---- raster::mdarray::tests::test_dimension_size stdout ----
thread 'raster::mdarray::tests::test_dimension_size' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:713:83

---- raster::mdarray::tests::test_n_dimension stdout ----
thread 'raster::mdarray::tests::test_n_dimension' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:659:83

---- raster::mdarray::tests::test_n_elements stdout ----
thread 'raster::mdarray::tests::test_n_elements' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:676:83

---- raster::mdarray::tests::test_no_data_value stdout ----
thread 'raster::mdarray::tests::test_no_data_value' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:816:83

---- raster::mdarray::tests::test_read_data stdout ----
thread 'raster::mdarray::tests::test_read_data' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:734:83

---- raster::mdarray::tests::test_read_string_array stdout ----
thread 'raster::mdarray::tests::test_read_string_array' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:754:85

---- raster::mdarray::tests::test_root_group_name stdout ----
thread 'raster::mdarray::tests::test_root_group_name' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:630:75

---- raster::mdarray::tests::test_spatial_ref stdout ----
thread 'raster::mdarray::tests::test_spatial_ref' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:794:83

---- raster::mdarray::tests::test_unit stdout ----
thread 'raster::mdarray::tests::test_unit' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALOpenEx", msg: "" }', src\raster\mdarray.rs:879:85

---- raster::tests::test_create_with_band_type_with_options stdout ----
thread 'raster::tests::test_create_with_band_type_with_options' panicked at 'called `Result::unwrap()` on an `Err` value: NullPointer { method_name: "GDALCreate", msg: "Attempt to create new tiff file `/tmp/test.tif' failed: No error" }', src\raster\tests.rs:311:14

---- vector::vector_tests::tests::test_write_features stdout ----
thread 'vector::vector_tests::tests::test_write_features' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process." }', src\vector\vector_tests\mod.rs:702:53


failures:
    raster::mdarray::tests::test_array_names
    raster::mdarray::tests::test_attributes
    raster::mdarray::tests::test_datatype
    raster::mdarray::tests::test_dimension_name
    raster::mdarray::tests::test_dimension_size
    raster::mdarray::tests::test_n_dimension
    raster::mdarray::tests::test_n_elements
    raster::mdarray::tests::test_no_data_value
    raster::mdarray::tests::test_read_data
    raster::mdarray::tests::test_read_string_array
    raster::mdarray::tests::test_root_group_name
    raster::mdarray::tests::test_spatial_ref
    raster::mdarray::tests::test_unit
    raster::tests::test_create_with_band_type_with_options
    vector::vector_tests::tests::test_write_features

test result: FAILED. 156 passed; 15 failed; 0 ignored; 0 measured; 0 filtered out; finished in 212.20s
```


and
```
test vector::vector_tests::tests::test_features_aliasing_compile_fail has been running for over 60 seconds
```

**Comment by pka** [comment]
cc @geohardtke @ChristianBeilschmidt

**Comment by ChristianBeilschmidt** [comment]
If all mdarray functions fail, maybe the GDAL version is too old and the compile guards don't work? :thinking:

**Comment by pka** [comment]
GDAL version is 3.4.3
