### ISSUE TITLE
Crash in `mdarray::tests::test_attributes`

### ISSUE THREAD

**Issue by lnicola** [georust/gdal#298]
```
core::slice::raw::from_raw_parts_mut::{closure#0}<*mut gdal_sys::GDALDimensionHS> () at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2128
2128	                    ::core::intrinsics::abort();
(gdb) bt
#0  core::slice::raw::from_raw_parts_mut::{closure#0}<*mut gdal_sys::GDALDimensionHS> () at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2128
#1  0x000055555565eda5 in core::ops::function::FnOnce::call_once<core::slice::raw::from_raw_parts_mut::{closure_env#0}<*mut gdal_sys::GDALDimensionHS>, ()> () at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248
#2  0x0000555555678613 in core::intrinsics::const_eval_select<(), fn(), core::slice::raw::from_raw_parts_mut::{closure_env#0}<*mut gdal_sys::GDALDimensionHS>, ()> (arg=(), _called_in_const=0x0, called_at_rt=...) at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2485
#3  0x0000555555643b31 in core::slice::raw::from_raw_parts_mut<*mut gdal_sys::GDALDimensionHS> (data=0x0, len=0) at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/raw.rs:137
#4  0x000055555564f0de in gdal::raster::mdarray::Group::dimensions (self=0x7fffd09f77a8, options=...) at src/raster/mdarray.rs:543
#5  0x00005555556770bc in gdal::raster::mdarray::tests::test_attributes () at src/raster/mdarray.rs:1047
#6  0x000055555560499a in gdal::raster::mdarray::tests::test_attributes::{closure#0} () at src/raster/mdarray.rs:1027
```

(line numbers might be slightly inaccurate because I have some local changes, all commented out)

**Comment by ChristianBeilschmidt** [comment]
Is this still an issue after https://github.com/georust/gdal/pull/302?

**Comment by lnicola** [comment]
Yes:

```
core::slice::raw::from_raw_parts_mut::{closure#0}<*mut gdal_sys::GDALDimensionHS> () at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2128
2128	                    ::core::intrinsics::abort();
(gdb) bt
#0  core::slice::raw::from_raw_parts_mut::{closure#0}<*mut gdal_sys::GDALDimensionHS> () at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2128
#1  0x000055555569b5f5 in core::ops::function::FnOnce::call_once<core::slice::raw::from_raw_parts_mut::{closure_env#0}<*mut gdal_sys::GDALDimensionHS>, ()> () at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248
#2  0x0000555555636a13 in core::intrinsics::const_eval_select<(), fn(), core::slice::raw::from_raw_parts_mut::{closure_env#0}<*mut gdal_sys::GDALDimensionHS>, ()> (arg=(), _called_in_const=0x0, called_at_rt=...) at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/intrinsics.rs:2485
#3  0x0000555555698a51 in core::slice::raw::from_raw_parts_mut<*mut gdal_sys::GDALDimensionHS> (data=0x0, len=0) at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/raw.rs:137
#4  0x0000555555602eee in gdal::raster::mdarray::Group::dimensions (self=0x7ffff1a507a8, options=...) at src/raster/mdarray.rs:541
#5  0x00005555555f3cd0 in gdal::raster::mdarray::tests::test_attributes () at src/raster/mdarray.rs:1073
#6  0x000055555567264a in gdal::raster::mdarray::tests::test_attributes::{closure#0} () at src/raster/mdarray.rs:1051
#7  0x000055555569cc9e in core::ops::function::FnOnce::call_once<gdal::raster::mdarray::tests::test_attributes::{closure_env#0}, ()> () at /home/grayshade/.rustup/toolchains/nightly-2022-08-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:248
```

604c41fbf62b96d0b44a14606b6f83b37db8059e
