### ISSUE TITLE
Debug-printing geometries segfaults

### ISSUE THREAD

**Issue by lnicola** [georust/gdal#365]
Something like:

```rust
fn main() -> Result<()> {
    let args = std::env::args().collect::<Vec<_>>();
    let point_ds = Dataset::open(&args[1])?;
    let mut layer = point_ds.layer(0)?;
    for feature in layer.features() {
        dbg!(feature);
    }
    Ok(())
}
```

crashes with:

```
[src/main.rs:17] feature = Feature {
    _defn: Defn {
        c_defn: 0x0000562e86c81c80,
    },
    c_feature: 0x0000562e86c85d60,
    geometry: [
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ~/.cargo/registry/src/github.com-1ecc6299db9ec823/gdal-0.14.0/src/vector/geometry.rs:177:38
stack backtrace:
   0: rust_begin_unwind
             at /rustc/efd27454ae94386e11997b1158f60d3a79deeb7d/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/efd27454ae94386e11997b1158f60d3a79deeb7d/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at /rustc/efd27454ae94386e11997b1158f60d3a79deeb7d/library/core/src/panicking.rs:114:5
   3: gdal::vector::geometry::Geometry::wkt
   4: <&T as core::fmt::Debug>::fmt
```

**Comment by metasim** [comment]
@lnicola Was going to replicate on MacOS. Can you share the input file?

**Comment by lnicola** [comment]
It happens with any input, like the sample from https://github.com/ngageoint/GeoPackage/blob/master/docs/examples/java/example.gpkg.

**Comment by metasim** [comment]
Not really the problem, but calling `unwrap` seems like a bad idea?

https://github.com/georust/gdal/blob/c7f88b56a855cfdff44267009f2ad1730cd03b14/src/vector/geometry.rs#L177

**Comment by metasim** [comment]
@lnicola I wonder if [this (`foreign_types`)](https://docs.rs/foreign-types/latest/foreign_types/index.html) or something like it might be worth considering. I think we need some principled semantics around these GDAL pointers, Rust has all the type machinery we need, we just need to find good examples of how to do this properly or rely on a library that does it for us.

**Comment by lnicola** [comment]
Still haven't looked into it, but I think we handle layers in a better way, that could serve as inspiration.

**Comment by metasim** [comment]
I have `foreign_types` prototype here: https://github.com/georust/gdal/compare/master...metasim:gdal:prototype/foreign_types

Personally, once I converted a couple types, I really liked it (except the paucity of documentation), especially since it explicitly distinguishes owned vs. borrowed types. However, there would be several breaking changes.
